adding status and more param

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -56,7 +56,21 @@ jobs:
           --document-name "AWS-RunShellScript" \
           --comment "Pulling docker image than run it" \
           --targets "Key=instanceids,Values="i-019ff13ea8e6fde5d,i-0b312705ae0a58c4c \
-          --parameters 'commands=["aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}"]' 
-          )
+          --parameters 'commands=["aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}",
+          "docker pull ${{ steps.login-aws-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO }}:latest",
+          "docker run --rm -d -p 3000:3000 ${{ steps.login-aws-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO }}:latest"
+          ]' 
+          --query "Command.CommandId" --output text)
 
-          echo "$command_id"
+          aws command wait command-executed 
+          --command-id $command_id \
+          --instance-id i-019ff13ea8e6fde5d,i-0b312705ae0a58c4c || true
+
+          status = $(aws ssm list-commands --command-id $command_id --query "Commands[0].StatusDetails" --output text)
+
+          if [ $status == "Success" ]; then
+            echo "Command executed successfully"
+          else
+            echo "Command failed"
+            exit 1
+          fi
