adding back if statement

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -64,14 +64,14 @@ jobs:
           --command-id $command_id \
           --instance-id ${{secrets.INSTANCE_ID_1}} || ${{secrets.INSTANCE_ID_2}}
 
-          commandOutput=$(aws ssm list-commands --command-id $command_id)
+          commandOutput=$(aws ssm list-commands --command-id $command_id -query "Commands[0].StatusDetails" --output text)
 
           echo $commandOutput
-        #--query "Commands[0].StatusDetails" --output text)
 
-        #if [ $status == "Success" ]; then
-        #echo "Command executed successfully"
-        #else
-        #echo "Command failed... time to debug"
-        #exit 1
-        #fi
+          if [ $commandOutput == "Success" ]; then
+            echo "Command executed successfully"
+          else
+            echo "Command failed... time to debug"
+            echo "$commandOutput"
+            exit 1
+          fi
